apiVersion: v1
kind: Pod
metadata:
  name: nodeport-nginx
  labels:
    env: dev
    project: roboshop
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: course-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    env: dev
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP