apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: roboshop
spec:
  selector:
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer