kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-roboshop-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b46283396ced773a
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-roboshop-sc
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-volume
          mountPath: "/usr/share/nginx/html"
      
      volumes:
      - name: nginx-volume
        persistentVolumeClaim: 
          claimName: roboshop-dynamic-pvc
