apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    component: frentend
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: nginx
      component: frentend
  template:
    metadata:
      labels:
        app: nginx
        component: frentend
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imeageVersion }}
        ports:
        - containerPort: 80
  