apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    tier: db
    project: roboshop
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
