apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    tier: app
    app: user
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      app: user
      project: roboshop
  template:
    metadata:
      labels:
        tier: app
        app: user
        project: roboshop
    spec:
      containers:
      - name: user
        image: joindevops/user:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    tier: app
    app: user
    project: roboshop
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO: true
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/users"